/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package queueclient;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author agung
 */
public class queClient extends javax.swing.JFrame {
    private String vDefault = "";
    private int vLayan = 100;
    private int vBayar = 200;
    private int total_antrian = 0;
    private int sisa_antrian = 0;
    private int nomor_antrian = 0;
    private int nomor_layanan = 0;
    private int status_antrian = 0;    
    private PropertyValues pv;
    private static String socketServer;
    private static int socketport;
    private static String loketname;
    private static String display;
    private static String pos;
    private static Properties prop;
    final int ST_LEWAT = 1;
    final int ST_LAYANAN = 2;
    final int ST_ISTIRAHAT = 3;
    /**
     * Creates new form queClient
     */
    public queClient() throws IOException {
        initComponents();
        pv = new PropertyValues();
        prop = new Properties(pv.getProperties());
        try{
           
        socketServer = prop.getProperty("SOCKET_SERVER");
        socketport = Integer.valueOf(prop.getProperty("SOCKET_SERVER_PORT"));
        loketname  = prop.getProperty("LOKETNAME");
        display  = prop.getProperty("DISPLAY");
        pos  = prop.getProperty("POS");
        jtxtLoket.setText(display);
         System.out.println(socketServer+" "+socketport);
        }
        finally{
            pv.closeProperties();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        jtxtLoket = new javax.swing.JTextField();
        ttlLayan = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        btnLayan = new javax.swing.JButton();
        btnPanggil = new javax.swing.JButton();
        btnIstirahat = new javax.swing.JButton();
        btnLewat = new javax.swing.JButton();
        lblnomor_antrian = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnl1.setBackground(new java.awt.Color(0, 51, 102));

        jtxtLoket.setEditable(false);
        jtxtLoket.setBackground(new java.awt.Color(0, 0, 51));
        jtxtLoket.setForeground(new java.awt.Color(255, 255, 204));
        jtxtLoket.setText("loket01");

        ttlLayan.setBackground(new java.awt.Color(0, 0, 0));
        ttlLayan.setFont(new java.awt.Font("DejaVu Sans", 1, 48)); // NOI18N
        ttlLayan.setForeground(new java.awt.Color(102, 102, 255));
        ttlLayan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ttlLayan.setText("100");
        ttlLayan.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "NOMOR LAYANAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 12), new java.awt.Color(102, 153, 255))); // NOI18N
        ttlLayan.setOpaque(true);

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLayan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tick_32.png"))); // NOI18N
        btnLayan.setText("Layan");
        btnLayan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLayan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayanActionPerformed(evt);
            }
        });
        pnl2.add(btnLayan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 200, 80));

        btnPanggil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sound.png"))); // NOI18N
        btnPanggil.setText("Panggil");
        btnPanggil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPanggil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanggilActionPerformed(evt);
            }
        });
        pnl2.add(btnPanggil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 200, 80));

        btnIstirahat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clock_32.png"))); // NOI18N
        btnIstirahat.setText("Tersedia");
        btnIstirahat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIstirahat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIstirahatActionPerformed(evt);
            }
        });
        pnl2.add(btnIstirahat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 80));

        btnLewat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/right_32.png"))); // NOI18N
        btnLewat.setText("Selanjutnya");
        btnLewat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLewat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLewatActionPerformed(evt);
            }
        });
        pnl2.add(btnLewat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 200, 80));

        lblnomor_antrian.setBackground(new java.awt.Color(0, 0, 0));
        lblnomor_antrian.setFont(new java.awt.Font("DejaVu Sans", 1, 48)); // NOI18N
        lblnomor_antrian.setForeground(new java.awt.Color(204, 0, 51));
        lblnomor_antrian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnomor_antrian.setText("100");
        lblnomor_antrian.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "NOMOR ANTRIAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        lblnomor_antrian.setOpaque(true);

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtLoket)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblnomor_antrian, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ttlLayan, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))))
            .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtLoket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttlLayan, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnomor_antrian, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl1Layout.createSequentialGroup()
                    .addGap(161, 161, 161)
                    .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLayanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayanActionPerformed
   try {
         //lblnomor_antrian.setText(tcpclient(loketname, "LAYAN",pos).trim());
         btnPanggil.setEnabled(false);
         ttlLayan.setText(tcpclient(loketname, "LAYAN",pos).trim());
         lblnomor_antrian.setForeground(Color.blue);
        } catch (Exception ex) {
            Logger.getLogger(queClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLayanActionPerformed

    private void btnPanggilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanggilActionPerformed
        try {
         lblnomor_antrian.setText(tcpclient(loketname, "PANGGIL",pos).trim());
         lblnomor_antrian.setForeground(Color.RED);
        } catch (Exception ex) {
            Logger.getLogger(queClient.class.getName()).log(Level.SEVERE, null, ex);
        }
  
    }//GEN-LAST:event_btnPanggilActionPerformed

    private void btnIstirahatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIstirahatActionPerformed
   try {
        if (btnIstirahat.getText().equals("Tersedia")) {    
            btnIstirahat.setText("Istirahat");
            tcpclient(loketname, "ISTIRAHAT",pos);
            btnLayan.setEnabled(false);
            btnPanggil.setEnabled(false);
            btnLewat.setEnabled(false);
        }
        else{
            btnIstirahat.setText("Tersedia");
            tcpclient(loketname, "TERSEDIA",pos);
            //btnLayan.setEnabled(true);
            // btnPanggil.setEnabled(true);
            btnLewat.setEnabled(true);
        }
        } catch (Exception ex) {
            Logger.getLogger(queClient.class.getName()).log(Level.SEVERE, null, ex);
        }  

    }//GEN-LAST:event_btnIstirahatActionPerformed

    private void btnLewatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLewatActionPerformed
        try {
         lblnomor_antrian.setText(tcpclient(loketname, "LEWAT",pos).trim());
         lblnomor_antrian.setForeground(Color.RED);
         btnPanggil.setEnabled(true);
         btnLayan.setEnabled(true);
        } catch (Exception ex) {
            Logger.getLogger(queClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLewatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try {
          vDefault = tcpclient(loketname, "DEFAULT",pos).trim();
          String[] split = vDefault.split("-");     
          lblnomor_antrian.setText(split[0]);
          ttlLayan.setText(split[1]);
        } catch (Exception ex) {
           Logger.getLogger(queClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(queClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(queClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(queClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(queClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    System.out.println(socketServer+' '+socketport);
                    new queClient().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(queClient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    private static String tcpclient(String loket, String type,String pos) throws Exception {
       // String sentence;
        String modifiedSentence;
        // BufferedReader inFromUser = new BufferedReader( new InputStreamReader(System.in));
        try (Socket clientSocket = new Socket(socketServer, socketport)) {
            DataOutputStream outToServer = new DataOutputStream(clientSocket.getOutputStream());
            BufferedReader inFromServer = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
            // sentence = inFromUser.readLine();
            outToServer.writeBytes(loket +"-"+type+"-"+pos+"\n");
            modifiedSentence = inFromServer.readLine();
            System.out.println(modifiedSentence);
        }
        return modifiedSentence;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIstirahat;
    private javax.swing.JButton btnLayan;
    private javax.swing.JButton btnLewat;
    private javax.swing.JButton btnPanggil;
    private javax.swing.JTextField jtxtLoket;
    private javax.swing.JLabel lblnomor_antrian;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JLabel ttlLayan;
    // End of variables declaration//GEN-END:variables
}
